### ISSUE TITLE
Order by commonness?

### ISSUE THREAD

**Issue by DanPen** [jacksonrayhamilton/wordlist-english#1]
Is there anyway to sort the words by their prevalence?

**Comment by jacksonrayhamilton** [comment]
There is only one pre-generated wordlist for each flavor of English.

I am not sure if more granularity is needed, although it would be pretty easy to get it. `wordlist['english']` could be equal to `wordlist['english/10'] + ... + wordlist['english/70']`, and `wordlist['english/80']` etc could be added for word game players.

Also, you can generate lists with larger proportions of more-commonly-used words by removing higher-rated sets of words from the generation script [here](https://github.com/jacksonrayhamilton/wordlist-english/blob/834bb52b2cd57638acbbab9bb3e7832fe7ff6a24/scripts/generate.js#L7), and then running that script.

From the [SCOWL readme](http://wordlist.aspell.net/scowl-readme/):

> Size 35 is the recommended small size, 50 the medium and 70 the large. For spell checking I recommend using 60.  Sizes 70 and below contain words found in most dictionaries . . .

**Comment by jacksonrayhamilton** [comment]
Unless you or someone else wants to make a case for more granularity, I'll assume 70 should be fine for most cases. Another possibility, perhaps preferable, would be for someone to publish "wordlist-english-simple," "wordlist-english-hippopotomonstrosesquipedaliophobia," each containing more common or more exotic words.

**Comment by jacksonrayhamilton** [comment]
@DanPen I ended up implementing this in 1.2.0.  From the current README:

> Words are further organized by their frequency of use.  Available frequency categories are 10, 20, 35, 40, 50, 55, 60, and 70.  The lower the number, the more frequently the word is believed to be used by English speakers.
> 
> ```js
> var commonEnglishWords = wordlist['english/10'];
> var bizarreEnglishWords = wordlist['english/70'];
> var commonAmericanWords = wordlist['english/american/10'];
> 
> commonEnglishWords.slice(555, 560)
> // => [ 'chooses', 'choosing', 'chose', 'chosen', 'church' ]
> 
> bizarreEnglishWords.slice(555, 560)
> // => [ 'aecium', 'aedes', 'aedile', 'aegrotat', 'aeneous' ]
> 
> commonAmericanWords.slice(10, 15)
> // => [ 'favor', 'favorite', 'flavor', 'gray', 'judgment' ]
> ```
