### ISSUE TITLE
Scrabble Friendly?

### ISSUE THREAD

**Issue by jim-alexander** [jacksonrayhamilton/wordlist-english#2]
Hey Jackson, 

Great library, I'm assuming that if i want to make a word puzzle game in Australia, all I would need to do is: 
`const wordArray = [...wordlist['english/australian'], ...wordlist['english']]`

Guess im asking, are all these words acceptable by some standard or do i need to filter again by frequency of use? 

Thanks

**Comment by jacksonrayhamilton** [comment]
Hi @jim-alexander,

Your example code will produce an array of words ranging from very-commonly-used words, to words “found in dictionaries.”

This code would produce an array of words only including very-commonly-used words:

```js
const wordArray = [...wordlist['english/australian/10'], ...wordlist['english/10']]
```

More words could be gradually added:

```js
const wordArray = [
  ...wordlist['english/australian/10'],
  ...wordlist['english/australian/20'],
  ...wordlist['english/australian/35'],
  ...wordlist['english/10'],
  ...wordlist['english/20'],
  ...wordlist['english/35']
]
```

…up to `/70`.

Words that one would probably _only_ find in word games were excluded from this package.  It sounds like you may have a case for including such words?

The words in this package are derived from SCOWL.  [Here is their README](http://wordlist.aspell.net/scowl-readme/), which explains more about the ratings of the words.  The words currently left out of this package are words like:

```
80: aidful antibourgeois bas bedash bolshevizes consolements electroanalytic
    entoiling glossographical hypopnea irrefrangibly lifeful macroaxes
    microseismometry nacarats pancheon pollinizations reroof topectomies
    troutperch tumblehome unconfessed undecidedness unfavorite voguishnesses 

95: adlumidine alinasal aramina begreen bembixes boundly cannibalean
    chondrinous colickiest cullas hartake interchangings marquito
    miscegenationists peremption quesitive ragnarok reconciliated sepsine
    sickless sigillaria staphyledema undelible unruth yaourti 
```

**Comment by jacksonrayhamilton** [comment]
Closing as this was asked a while ago.
